### ISSUE TITLE
email notifications for check list

### ISSUE THREAD

**Issue by mmaker86** [RCRM/redmine_checklists#7]
Hi, 
is still exist email notifications after create/update/close check list boxes ? I run version 3.1.3 , and there is no settings to make notifications.

**Comment by mmaker86** [comment]
I'll try to ask again :)
Does light version of checklist plugin  have notifications by email feature?

**Comment by sergeyz** [comment]
Hi, you can try http://www.redminecrm.com/questions ask here

> This is an automatically updated unofficial mirror of the RedmineCRM (http://redminecrm.com/) plugins
